version: 0.2

env:
  variables:
     projectName: "CounterApp"
     mavenGoal: "install"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      nodejs: 20
      # name: version
    commands:
       - "apt update && apt -y install tree"
      # - command
  pre_build:
    commands:
       - "npm install"
      # - command
  build:
    commands:
       - npm run build --if-present
       - ls -lart
       - npm run test
       - node -v
  post_build:
    commands:
       - "npm run test:e2e"
       - "zip -r dist.zip dist"
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
     # - "dist.zip"
     - "dist/*"     
  name: $(date +%Y-%m-%d)
  discard-paths: yes
  base-directory: .
#cache:
  #paths:
    # - paths
#test commit
